name: Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        name: deploy

        steps:
            - name: Publish package
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
              run: |
                  echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
                  npm publish
