name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish to NPM (only if version changed)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Get current version
        id: current_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Get previous version
        id: previous_version
        run: |
          git fetch --depth=2 origin main
          echo "version=$(git show HEAD^:package.json | jq -r .version)" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: version_check
        run: |
          echo "Current: ${{ steps.current_version.outputs.version }}"
          echo "Previous: ${{ steps.previous_version.outputs.version }}"
          if [ "${{ steps.current_version.outputs.version }}" == "${{ steps.previous_version.outputs.version }}" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish package
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
